#!/usr/bin/env bash

# Update apt package index and install nginx with the
# "-y" flag to automatically confirm prompts
apt-get update
apt-get install -y nginx

# Configure nginx to listen on port 80
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        return 200 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

# Restart nginx without using systemctl
nginx -s reload
