#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  yonas-frontend
        bind *:80
        mode http
        default_backend yonas-backend
backend yonas-backend
        balance roundrobin
        server 529896-web-01 54.89.134.78:80 check
        server 529896-web-02 52.87.215.154:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
