#!/usr/bin/env bash

# Check if script is running with root privileges
if [ "$(id -u)" -ne 0 ]; then
    echo "Please run this script with sudo or as root."
    exit 1
fi

# Update package repositories and install HAProxy
apt-get -y update
apt-get -y install haproxy

# Define server configuration
server_config='
listen 529896-lb-01
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 529896-web-01 100.25.17.146:80 check
    server 529896-web-02 54.209.46.98:80 check
'

# Create directory if it doesn't exist
mkdir -p /etc/haproxy

# Write server configuration to haproxy.cfg
echo "$server_config" | tee /etc/haproxy/haproxy.cfg

# Enable HAProxy service
echo "ENABLED=1" | tee -a /etc/default/haproxy

# Restart HAProxy service
service haproxy restart
