#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server

if [ "$(id -u)" -ne 0 ]; then
    echo "Please run this script with sudo or as root."
    exit 1
fi

apt-get update
apt-get install -y haproxy

cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 529896-web-01 100.25.17.146:80 check
    server 529896-web-02 54.209.46.98:80 check
EOF

sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

service haproxy restart

service haproxy status
